Update sbom.yaml

diff --git a/.github/workflows/sbom.yaml b/.github/workflows/sbom.yaml
--- a/.github/workflows/sbom.yaml
+++ b/.github/workflows/sbom.yaml
@@ -170,52 +170,52 @@ jobs:
           
   verify-dependency-list:
     runs-on: ubuntu-latest
-    needs: generate-sbom
-
     steps:
-    
-      # Download the SBOM artifact
-      - name: Download SBOMs
-        uses: actions/download-artifact@v4
-        with:
-          name: sbom
-      
-      # Download managed dependencies from a remote JSON file
-      - name: Download managed dependencies
-        run: |
-          curl -H "Authorization: token ${TOKEN}" \
-               -L https://raw.githubusercontent.com/DPaaS-organization/DPaaS-Admin-Repo/main/managed-dependencies.json \
-               -o managed-dependencies.json -vv
-        env:
-          TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    # Download the SBOM artifact
+    - name: Download SBOMs
+      uses: actions/download-artifact@v4
+      with:
+        name: sbom
 
-      # Extract dependencies from the SBOM
-      - name: Extract Dependencies from SBOM
-        run: |
-          jq -r '.components[].name' sbom.json > sbom-dependencies.txt
+    # Download managed dependencies from a remote JSON file
+    - name: Download Managed Dependencies
+      run: |
+        curl -H "Authorization: token ${TOKEN}" \
+             -L https://raw.githubusercontent.com/DPaaS-organization/DPaaS-Admin-Repo/main/managed-dependencies.json \
+             -o managed-dependencies.json -vv
+      env:
+        TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Debugging: List files and contents
-      - name: Debug File
-        run: |
-          ls -lh
-          cat managed-dependencies.json
-      
-      # Extract managed dependencies from the downloaded JSON
-      - name: Extract Managed Dependencies
-        run: |
-          jq -r 'keys[]' managed-dependencies.json > managed-dependencies.txt
+    # Validate the structure of the managed dependencies JSON file
+    - name: Validate JSON
+      run: |
+        jq empty managed-dependencies.json || (echo "Invalid JSON" && exit 1)
 
-      # Verify that all SBOM dependencies are in the managed dependencies list
-      - name: Verify Dependencies
-        run: |
-          # Compare the two lists
-          if ! comm -12 <(sort sbom-dependencies.txt) <(sort managed-dependencies.txt) > /dev/null; then
-            echo "Some dependencies are not in the managed dependencies list."
-            exit 1
-          fi
+    # Extract dependencies from the SBOM
+    - name: Extract Dependencies from SBOM
+      run: |
+        jq -r '.components[].name' sbom.json > sbom-dependencies.txt
 
-    
-  
+    # Debugging: List files and contents
+    - name: Debug File Content
+      run: |
+        ls -lh
+        cat managed-dependencies.json
+
+    # Extract managed dependencies from the downloaded JSON
+    - name: Extract Managed Dependencies
+      run: |
+        jq -r 'keys[]' managed-dependencies.json > managed-dependencies.txt
+
+    # Verify that all SBOM dependencies are in the managed dependencies list
+    - name: Verify Dependencies
+      run: |
+        # Compare the two lists
+        if ! comm -12 <(sort sbom-dependencies.txt) <(sort managed-dependencies.txt) > /dev/null; then
+          echo "Some dependencies are not in the managed dependencies list."
+          exit 1
+        fi
+        
   fetch-scan-from-dependency-track:
     runs-on: self-hosted
     needs: push-sbom # Ensures this job runs only after push-sbom is complete
