Update sbom.yaml

diff --git a/.github/workflows/sbom.yaml b/.github/workflows/sbom.yaml
--- a/.github/workflows/sbom.yaml
+++ b/.github/workflows/sbom.yaml
@@ -179,14 +179,25 @@ jobs:
       with:
         name: sbom
 
-    # Download managed dependencies from a remote JSON file
-    - name: Download Managed Dependencies
+    - name: Debug Managed Dependencies Download
       run: |
         curl -H "Authorization: token ${TOKEN}" \
              -L https://raw.githubusercontent.com/DPaaS-organization/DPaaS-Admin-Repo/main/managed-dependencies.json \
              -o managed-dependencies.json -vv
+        echo "Downloaded file content:"
+        cat managed-dependencies.json || echo "Download failed or file is empty"
       env:
         TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+    # # Download managed dependencies from a remote JSON file
+    # - name: Download Managed Dependencies
+    #   run: |
+    #     curl -H "Authorization: token ${TOKEN}" \
+    #          -L https://raw.githubusercontent.com/DPaaS-organization/DPaaS-Admin-Repo/main/managed-dependencies.json \
+    #          -o managed-dependencies.json -vv
+    #   env:
+    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
     - name: Debug `managed-dependencies.json`
