Update sonarqube-workflow.yaml

diff --git a/.github/workflows/sonarqube-workflow.yaml b/.github/workflows/sonarqube-workflow.yaml
--- a/.github/workflows/sonarqube-workflow.yaml
+++ b/.github/workflows/sonarqube-workflow.yaml
@@ -114,14 +114,14 @@ jobs:
             fi
           done
       
-      # Verify whether the scan meets the criteria in the Quality gate set up in SonarQube.
-      # When the Quality Gate is not met, an error is given and the build is blocked.
-      - name: Check Quality Gate
-        run: |
-          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }} \
-            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
-            | jq -r '.projectStatus.status')
-          if [ "$STATUS" != "OK" ]; then
-            echo "::error ::Quality gate failed: $STATUS"
-            exit 1  # Exit with error
-          fi
+      # # Verify whether the scan meets the criteria in the Quality gate set up in SonarQube.
+      # # When the Quality Gate is not met, an error is given and the build is blocked.
+      # - name: Check Quality Gate
+      #   run: |
+      #     STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }} \
+      #       "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
+      #       | jq -r '.projectStatus.status')
+      #     if [ "$STATUS" != "OK" ]; then
+      #       echo "::error ::Quality gate failed: $STATUS"
+      #       exit 1  # Exit with error
+      #     fi
